# Generated by Django 3.1.7 on 2021-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=10)),
                ('contact', models.IntegerField()),
                ('district', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
